name: Upload data to prod database on prerelease

on:
  release:
    types: [published]

jobs:
  publish:
    uses: Geological-Survey-of-Western-Australia/Vocabularies/.github/workflows/upload-to-database.yml@main
    with:
      environment: prod
      request_timeout: 300
    secrets:
      prez_url: ${{ secrets.PREZ_URL }}
      database_url: ${{ secrets.FUSEKI_DATASET_URL }}
      database_username: ${{ secrets.FUSEKI_USERNAME }}
      database_password: ${{ secrets.FUSEKI_PASSWORD }}
